language: python

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libevent-dev libev-dev git-core

python:
  - "2.6"
  - "2.7"

install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install

before_script:
  - git clone git://github.com/sockjs/sockjs-protocol.git sockjs_protocol
  - pip install unittest2 websocket-client==0.4.1 git+git://github.com/Lawouach/WebSocket-for-Python.git --use-mirrors

script:
  - nosetests
  # run the sockjs-protocol tests
  - python tests/run_protocol_tests.py sockjs_protocol 0.3.3
