language: python

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq git-core

python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install

before_script:
  - git clone git://github.com/sockjs/sockjs-protocol.git sockjs_protocol

script:
  - nosetests
  # run the sockjs-protocol tests
  - python tests/run_protocol_tests.py sockjs_protocol 0.3.3
